exports.productList = [
    {
        name: 'Muscadet Tee',
        description: 'fucking nice t shirt',
        tag: '1',
        price: 48,
        size: 0,
        inCart: 0,
        image: 'https://i.ibb.co/PFW4Zcd/1.jpg',
        url: 'Product-1'
    },
    {
        name: 'Original Tee',
        description: 'fucking nice t shirt',
        tag: '2',
        price: 48,
        size: 0,
        inCart: 0,
        image: 'https://i.ibb.co/wgCDpKW/2.jpg',
        url: 'Product-2',
    },
    {
        name: 'Manifest Tee',
        description: 'fucking nice t shirt',
        tag: '3',
        size: 0,
        price: 48,
        inCart: 0,
        image: 'https://i.ibb.co/VVBm4Fq/3.jpg',
        url: 'Product-3',
    },
    {
        name: 'sunrise Tee',
        description: 'fucking nice t shirt',
        tag: '4',
        size: 0,
        price: 48,
        inCart: 0,
        image: 'https://i.ibb.co/n6X8THn/4.jpg',
        url: 'Product-4',
    },
    {
        name: 'create Tee',
        description: 'fucking nice t shirt',
        tag: '5',
        size: 0,
        price: 48,
        inCart: 0,
        image: 'https://i.ibb.co/Lr8N9K4/5.jpg',
        url: 'Product-5',
    },
    {
        name: 'Flame Tee',
        description: 'fucking nice t shirt',
        tag: '6',
        size: 0,
        price: 48,
        inCart: 0,
        image: 'https://i.ibb.co/ySgSFp7/6.jpg',
        url: 'Product-6.',
    },
    /*
    {
        name: 'Mastermind Hat',
        description: 'fucking nice t shirt',
        tag: '12_01_updatefinal_1500xd26d',
        size: 'one size',
        price: 20,
        inCart: 0,
        image: 'https://i.ibb.co/ry7p6S7/DJ0619-133-258114212-D-A-1-X1-1af16477-3b3d-48ec-a22b-7527d50e3727-1500xe5f4.jpg',
        url: 'roger-roger-mastermind-hat',
    },

    /*   {
        name: '3 pack socks',
        description: 'fucking nice t shirt',
        tag: 'EXTRA_SOCKS_01_1500x6852',
        size: 'one size',
        price: 20,
        inCart: 0,
        image: 'https://i.ibb.co/51WpJCC/EXTRA-SOCKS-01-1500x6852.jpg',
        url: 'roger-roger-basic-3pack-socks',

    }*/
]