exports.productList = [
    {
        name: 'Kodes',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '1',
        price: 14,
        size: 0,
        inCart: 0,
        image: 'https://i.ibb.co/nQQv2rL/1.jpg',
        url: 'Product-1'
    },
    {
        name: 'Rad Cartier',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '2',
        price: 14,
        size: 0,
        inCart: 0,
        image: 'https://i.ibb.co/87yd6M7/2.jpg',
        url: 'Product-2',
    },
    {
        name: 'Chanceko',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '3',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/SmY75Zf/3.jpg',
        url: 'Product-3',
    },
    {
        name: 'Edge',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '4',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/2Fbw3Ty/4.jpg',
        url: 'Product-4',
    },
    {
        name: 'Dimeh',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '5',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/jJX3fPH/5.jpg',
        url: 'Product-5',
    },
    {
        name: 'Thahomey',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '6',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/6RhG9Fm/6.jpg',
        url: 'Product-6',
    },
    {
        name: 'Sonbest',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '7',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/bJWVSYF/7.jpg',
        url: 'Product-7',
    },
    {
        name: 'Sonbest1',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '8',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/zFmNfWd/8.jpg',
        url: 'Product-8',
    },
    {
        name: 'Sonbest2',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '9',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/2yj2PLg/9.jpg',
        url: 'Product-9',
    },
    {
        name: 'Slimka',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '10',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/Ltjk5BG/10.jpg',
        url: 'Product-10',
    },
    {
        name: 'Ichon',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '11',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/GHPStJz/11.jpg',
        url: 'Product-11',
    },
    {
        name: 'Ichon1',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '12',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/z4tmJN7/12.jpg',
        url: 'Product-12',
    },
    {
        name: 'Squidji',
        description: 'Tirage satiné en 30,5cm par 40,7cm',
        tag: '13',
        size: 0,
        price: 14,
        inCart: 0,
        image: 'https://i.ibb.co/vsp63tj/13.jpg',
        url: 'Product-13',
    },
    /*
    {
        name: 'Mastermind Hat',
        description: 'fucking nice t shirt',
        tag: '12_01_updatefinal_1500xd26d',
        size: 'one size',
        price: 20,
        inCart: 0,
        image: 'https://i.ibb.co/ry7p6S7/DJ0619-133-258114212-D-A-1-X1-1af16477-3b3d-48ec-a22b-7527d50e3727-1500xe5f4.jpg',
        url: 'roger-roger-mastermind-hat',
    },

    /*   {
        name: '3 pack socks',
        description: 'fucking nice t shirt',
        tag: 'EXTRA_SOCKS_01_1500x6852',
        size: 'one size',
        price: 20,
        inCart: 0,
        image: 'https://i.ibb.co/51WpJCC/EXTRA-SOCKS-01-1500x6852.jpg',
        url: 'roger-roger-basic-3pack-socks',

    }*/
]